ragflow:
  host: 0.0.0.0
  http_port: 9380
es:
  hosts: 'http://172.16.203.188:9200'
  username: 'elastic'
  password: 'admin123'
postgres:
  host: '172.16.203.188'
  port: 5432
  user: 'postgres'
  password: 'admin123'
  name: 'easymind'
  max_connections: 100
  stale_timeout: 30
redis:
  host: '172.16.203.188:6379'
  password: 'admin123'
  db: 1
oss:
  access_key: ''
  secret_key: ''
  endpoint_url: 'https://oss-cn-hangzhou.aliyuncs.com'
  region: 'oss-cn-hangzhou'
  bucket: ''
  prefix_path: 'easymind'